#!/bin/bash
# This script is designed for PAL

##########################################
#FIXME: change to PAL direcotry
# Cheetah
export CDIR=/reg/neh/home/yoon82/temp/cheetah
# HDF5
export HDF5_ROOT=/reg/neh/home/yoon82/temp/hdf5_1.8.10-patch1_pthread
# CMAKE
export PATH=/reg/neh/home/yoon82/temp/cmake/bin:${PATH}
# Python3
export ADIR=/reg/neh/home/yoon82/anaconda3
##########################################

echo Setting up Cheetah
echo Using ${CDIR}
export PATH=${CDIR}/bin:$PATH

echo Deleting old build directory
rm -rf build
rm -rf CMakeCache.txt CMakeFiles
echo Creating new build directory
mkdir build
cd build

cmake .. -DBUILD_CHEETAH_PAL=ON \
         -DFIND_HL=ON\
         -DBUILD_PSANA=OFF \
         -DCMAKE_BUILD_TYPE=Release \
         -DCMAKE_INSTALL_PREFIX=${CDIR}
echo ""
echo ""
read -p "Finished. Press any key to open ccmake and double check all settings. Remember to set CMAKE_INSTALLATION_PREFIX to the install directory " -n1 -s
ccmake ../
echo ""
echo ""
echo "********** IMPORTANT ************"
echo Done, now change into the build directory, then type make and make install
echo "**********************************"
